### ISSUE TITLE
parseTimestamp and parseIcsEvent should accept VTimezone[] | undefined

### ISSUE THREAD

**Issue by dbondarchuk** [Neuvernetzung/ts-ics#42]
The timestamps parsed by parseTimestamp are off, as they ignore the timezone.

By providing the optional `VTimezone[]` we can properly calculate the date & time.
If `parseEvent` was called by `parseCalendar` it can do it automatically

**Comment by dbondarchuk** [comment]
`parseTimestamp` should always return UTC time and ideally provide the time zone offset in the return object

**Comment by timheerwagen** [comment]
I absolutely agree with you there. I will have a look at it soon.

**Comment by dbondarchuk** [comment]
Maybe we can look on https://github.com/kewisch/ical.js/blob/main/lib/ical/timezone.js for the implementation?

**Comment by timheerwagen** [comment]
To be honest, timezones in ics are scary, so I had waited with the implementation for the time being.

So optional `VTimezone[]` must be passed with every `generateIcsTimeStamp` and `parseicsTimeStamp`.

We could use `date-fns-tz` for better Tz handling instead of using a giant Timezone Array like other ics packages and add tzoffset as fallback. I hope this does not bloat the bundle size.

New DateObject Type would be:

```
export type DateObject = {
  date: Date;
  type?: DateObjectType;
  timezone?: string;
  tzoffset?: string
};
```

If this is urgent for you, feel free to post a PR and I'll take a look at it tomorrow.

**Comment by dbondarchuk** [comment]
We can use `date-fns-ts` for handling the add of the timezone and fall back to getting the timezone by its name (also remember that Outlook uses Windows names -> we also need to try converting the name from Windows to IANA as a second fallback). But we should try to find the zone by id in the array of `VTIMEZONE` if it's passed to us and grab the offset from there (based on daylight/standard/etc), as it is possible to have non IANA/Windows zones

**Comment by dbondarchuk** [comment]
the flow should be like this:
1) try to find zone in `VTIMEZONE[]` if it was passed down and get the current offset
2) If no timezones passed, try `date-fns-tz` to get the timezone by name
3) If fails, try to map it from Windows to IANA
4) If fails, return as UTC

The return object can look like this:
```typescript
export type DateObject = {
  date: Date; // we can decide UTC or provided TZ (or maybe we can have two fields?)
  type?: DateObjectType;
  timezone?: string; // the one from the value string OR from fns package if fallback
  tzoffset?: string; // offset in minutes if successfully got timezone
};
```

The main problem here, that because time in the string value IS in the timezone and we parse it into UTC

**Comment by timheerwagen** [comment]
The flow looks good to me.

I had similar thoughts to provide 2 fields, but that brings a bit of extra logic to the DateObject creation. 

My ideas would be:

```
export type DateObject = {
  date: Date; // UTC
  type?: DateObjectType;
  local?: Date; // TZ
  timezone?: string; // the one from the value string OR from fns package if fallback
  tzoffset?: string; // offset in minutes if successfully got timezone
};
```

Or in an extra object, which I like even a bit better.

```
export type DateObject = {
  date: Date; // UTC
  type?: DateObjectType;
  local?: {
    date: Date; // TZ
    timezone: string; // the one from the value string OR from fns package if fallback
    tzoffset: string; // offset in minutes if successfully got timezone
  }
};
```

Yes, parsing the TZ Date to UTC is incorrect there.

My last question would be how we can convert Windows Timezones?

**Comment by dbondarchuk** [comment]
Not many options to convert from Windows to IANA. Just the plain mapping: https://github.com/rubenillodo/windows-iana/blob/master/src/data/windowsToIanaMap.ts

If you fear the bloated package size, another option would be to have 3rd argument to provide a fallback function that returns  `(offset / IANA  timezone name) | undefined` from the string, and users can decide do they really care about the slim chance of not having the timezone properly parsed from the ics itself

**Comment by timheerwagen** [comment]
That thing is huge. Even though I think most of the time it runs on the server, bundle size could be an issue.

That sounds like a good compromise.

**Comment by dbondarchuk** [comment]
Yeah, in 99.9999% of the cases it is not needed, so just a back up function should suffice

**Comment by timheerwagen** [comment]
I will have a look at this now. First i'll implement step 1,2 and 4.

If you want, you can make a contribution for the fallback function later. We also need some tests.

**Comment by timheerwagen** [comment]
I merged to `develop` branch. Feel free to look in to see if this provides the functionality we need.

Since we currently do not handle recurrence, i prefer IANA over the VTIMEZONES object.
If Ms-Outlook passes the used Microsoft Timezones as VTIMEZONE it should correctly be parsed.

**Comment by dbondarchuk** [comment]
Looked into the usage with Outlook timezones and it seemed correct!

**Comment by timheerwagen** [comment]
Great, I will release v1.1 now then.
