### ISSUE TITLE
Unescaping commas in values

### ISSUE THREAD

**Issue by danielbuechele** [Neuvernetzung/ts-ics#82]
I'm not sure if this follows the spec, but Google for example in their ICS files escapes commas with `\`. For example: `LOCATION: 1600 Amphitheatre Parkway\, Mountain View\, California\, 94043`.
The escape character is not removed from the parsed string. so it ends up as: `{"location": "1600 Amphitheatre Parkway\, Mountain View\, California\, 94043"}`

Should we add unescaping to the parser?

**Comment by timheerwagen** [comment]
Thank you for the suggestion.

I have just had a look. In the example of RFC5545 https://icalendar.org/iCalendar-RFC-5545/3-8-1-7-location.html the location is also with backslash. `LOCATION:Conference Room - F123\, Bldg. 002`. 

However, Google uses this to parse the address and I know of no other field where backslashes are used to escape commas.

When importing, Google accepts the address with and without backslash escaped commas.

So I would suggest leaving the parsing of the address entirely to the end user, although the early removal of the backslashes could be a problem.
